version: '3.8'

services:
  redis:
    image: redis:8.0.0  # Updated to use Redis 8 container
    container_name: redis-benchmarker
    ports:
      - "6379:6379"
      - "8001:8001"  # RedisInsight UI
    environment:
      - REDIS_ARGS=--save 60 1000 --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
    driver: local